name: COSMO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9426523
title: Cosmo - as an art project in the spirit of a love letter to my son - will produce 21 works of art (reflecting his 21yrs of life) to be presented to him on the night of his 21st birthday. This site will journal the production of these works of art and record the thoughts of his father and those collaborating on the project throughout its creation.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8100358
  lightness: 0.2706093
  saturation: 0.5232975
  rhythmicContrast: 0.8064516
purpose: []
