typography_spectrum: 0.9426523
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 1
title: Cosmo - as an art project in the spirit of a love letter to my son - will produce 21 works of art (reflecting his 21yrs of life) to be presented to him on the night of his 21st birthday. This site will journal the production of these works of art and record the thoughts of his father and those collaborating on the project throughout its creation.
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5232975
  brandStrength: 0.8100358
  rhythmicContrast: 0.8064516
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.2706093
purpose: []
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: COSMO
