layout_spectrum: 1
typography_spectrum: 0.9426523
color:
  saturation: 0.5232975
  lightness: 0.2706093
  brandStrength: 0.8100358
  rhythmicContrast: 0.8064516
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: COSMO
