name: COSMO
favicon: null
layout_spectrum: 0.26596
typography_spectrum: 0.9426523
title: Cosmo
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#786016'
    - '#39331d'
    - '#a88939'
    - '#d0c077'
  brandStrength: 0.8100358
  lightness: 0.2706093
  saturation: 0.5232975
  rhythmicContrast: 0.75
purpose: []
