analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
title: Cosmo
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5232975
  brandStrength: 0.8100358
  rhythmicContrast: 0.8064516
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.2706093
purpose: []
favicon: null
name: COSMO
typography_spectrum: 0.9426523
